Repository scalar-labs/helm-charts, pull requests merged in 2021-08, with the labels that each got.

#13 Add configmap for grafana dashboard
  charts/scalardl/Chart.yaml
  charts/scalardl/README.md
  charts/scalardl/files/envoy_grafana_dashboard.json
  charts/scalardl/files/scalardl_grafana_dashboard.json
  charts/scalardl/templates/envoy/configmap.yaml
  charts/scalardl/templates/ledger/configmap.yaml
  charts/scalardl/values.yaml
Labels: improvement

#14 Update scalar-envoy to 1.1.0
  charts/scalardl/Chart.yaml
  charts/scalardl/README.md
  charts/scalardl/values.yaml
Labels: enhancement

#12 Add Helm chart for Scalar DB
  README.md
  charts/scalardb/.helmignore
  charts/scalardb/Chart.yaml
  charts/scalardb/README.md
  charts/scalardb/README.md.gotmpl
  charts/scalardb/files/scalardb_grafana_dashboard.json
  charts/scalardb/templates/_helpers.tpl
  charts/scalardb/templates/configmap.yaml
  charts/scalardb/templates/deployment.yaml
  charts/scalardb/templates/prometheusrules.yaml
  charts/scalardb/templates/service.yaml
  charts/scalardb/templates/servicemonitor.yaml
  charts/scalardb/values.yaml
Labels: enhancement

#15 Update Chart.yaml
  charts/scalardl/Chart.yaml
  charts/scalardl/README.md
  charts/schema-loading/Chart.yaml
  charts/schema-loading/README.md
Labels: documentation

#17 Update to make it runnable without custom config and make auditor work
  charts/schema-loading/README.md
  charts/schema-loading/templates/batchjob-schema-loading.yaml
  charts/schema-loading/values.yaml
Labels: improvement
