Repository scalar-labs/helm-charts, pull requests merged in 2022-08, with the labels that each got.

#124 Update Auditor chart to use `40053` port for scalar-admin by default
  charts/scalardl-audit/README.md
  charts/scalardl-audit/templates/auditor/deployment.yaml
  charts/scalardl-audit/values.yaml
Labels: improvement

#110 Add monitoring resources to scalardb-graphql chart
  charts/scalardb-graphql/README.md
  charts/scalardb-graphql/templates/scalardb-graphql/prometheusrules.yaml
  charts/scalardb-graphql/templates/scalardb-graphql/service.yaml
  charts/scalardb-graphql/templates/scalardb-graphql/servicemonitor.yaml
  charts/scalardb-graphql/values.yaml
Labels: enhancement

#113 Update default Ingress paths configuration in values.yaml
  charts/scalardb-graphql/README.md
  charts/scalardb-graphql/values.yaml
Labels: improvement

#125 Update chart version to keep main branch latest (Envoy)
  charts/envoy/Chart.yaml
  charts/envoy/README.md
Labels: bugfix

#126 Update chart version to keep main branch latest (Ledger)
  charts/scalardl/Chart.lock
  charts/scalardl/Chart.yaml
  charts/scalardl/README.md
  charts/scalardl/values.yaml
Labels: bugfix

#127 Update chart version to keep main branch latest (Auditor)
  charts/scalardl-audit/Chart.lock
  charts/scalardl-audit/Chart.yaml
  charts/scalardl-audit/README.md
  charts/scalardl-audit/values.yaml
Labels: bugfix

#111 Add provisioned Grafana dashboard to scalardb-graphql Helm chart
  charts/scalardb-graphql/README.md
  charts/scalardb-graphql/files/grafana/scalardb_graphql_grafana_dashboard.json
  charts/scalardb-graphql/templates/scalardb-graphql/configmap.yaml
  charts/scalardb-graphql/values.yaml
Labels: enhancement

#129 Update chart version to keep main branch latest (Ledger)
  charts/scalardl/Chart.yaml
  charts/scalardl/README.md
  charts/scalardl/values.yaml
Labels: bugfix

#130 Update chart version to keep main branch latest (Auditor)
  charts/scalardl-audit/Chart.yaml
  charts/scalardl-audit/README.md
  charts/scalardl-audit/values.yaml
Labels: bugfix

#128 Add values.schema.json to scalardb-graphql chart
  charts/scalardb-graphql/README.md
  charts/scalardb-graphql/values.schema.json
  charts/scalardb-graphql/values.yaml
Labels: improvement

#131 Add samples for deployment of Scalar DB/DL using Helm Chart
  docs/samples/scalardb/scalardb-multi-storage-sample/README.md
  docs/samples/scalardb/scalardb-multi-storage-sample/database.properties
  docs/samples/scalardb/scalardb-multi-storage-sample/scalardb-server.yaml
  docs/samples/scalardb/scalardb-multi-storage-sample/scalardb-sql-cli.yaml
  docs/samples/scalardl/scalardl-auditor-mode-sample/README.md
  docs/samples/scalardl/scalardl-auditor-mode-sample/auditor-key.pem
  docs/samples/scalardl/scalardl-auditor-mode-sample/auditor.as.client.properties
  docs/samples/scalardl/scalardl-auditor-mode-sample/auditor.pem
  docs/samples/scalardl/scalardl-auditor-mode-sample/client-key.pem
  docs/samples/scalardl/scalardl-auditor-mode-sample/client.pem
  docs/samples/scalardl/scalardl-auditor-mode-sample/client.properties
  docs/samples/scalardl/scalardl-auditor-mode-sample/ledger-key.pem
  docs/samples/scalardl/scalardl-auditor-mode-sample/ledger.as.client.properties
  docs/samples/scalardl/scalardl-auditor-mode-sample/ledger.pem
  docs/samples/scalardl/scalardl-auditor-mode-sample/scalardl-auditor-custom-values.yaml
  docs/samples/scalardl/scalardl-auditor-mode-sample/scalardl-client.yaml
  docs/samples/scalardl/scalardl-auditor-mode-sample/scalardl-ledger-custom-values.yaml
  docs/samples/scalardl/scalardl-auditor-mode-sample/schema-loader-auditor-custom-values.yaml
  docs/samples/scalardl/scalardl-auditor-mode-sample/schema-loader-ledger-custom-values.yaml
Labels: documentation

#132 Update scalardb-graphql version to 3.6.0
  .github/schema-loading.yaml
  .github/workflows/helm_charts_scalar.yml
  charts/scalardb-graphql/Chart.yaml
  charts/scalardb-graphql/README.md
  charts/scalardb-graphql/ci/ct-values.yaml
  charts/scalardb-graphql/templates/scalardb-graphql/deployment.yaml
  charts/scalardb-graphql/values.yaml
Labels: improvement

#133 Add Scalar DL chart to the list of targets for testing of kubeaudit
  .github/workflows/helm_charts_scalar.yml
Labels: improvement

#135 Fix bug of CI related to the kubeaudit
  .github/workflows/helm_charts_scalar.yml
Labels: bugfix
