Repository scalar-labs/helm-charts, pull requests merged in 2022-05, with the labels that each got.

#88 Add `-n monitoring` flag to `helm uninstall` command
  docs/getting-started-monitoring.md
Labels: bugfix

#87 Add the `loki-stack` part
  docs/conf/scalar-loki-stack-custom-values.yaml
  docs/getting-started-logging.md
Labels: improvement

#85 Add Getting Started Guide with Helm Chart (Scalar DL)
  docs/getting-started-scalardl-auditor.md
  docs/getting-started-scalardl-ledger.md
Labels: documentation

#90 Fix the incorrect spelled POD
  docs/conf/scalar-loki-stack-custom-values.yaml
Labels: documentation

#91 Separates the redundancy part and Update index
  docs/README.md
  docs/getting-started-monitoring.md
  docs/getting-started-scalar-helm-charts.md
  docs/getting-started-scalardb.md
  docs/getting-started-scalardl-auditor.md
  docs/getting-started-scalardl-ledger.md
Labels: documentation

#92 Update version of each chart to latest
  charts/envoy/Chart.yaml
  charts/envoy/README.md
  charts/scalardb/Chart.lock
  charts/scalardb/Chart.yaml
  charts/scalardb/README.md
  charts/scalardb/values.yaml
  charts/scalardl-audit/Chart.lock
  charts/scalardl-audit/Chart.yaml
  charts/scalardl-audit/README.md
  charts/scalardl-audit/values.yaml
  charts/scalardl/Chart.lock
  charts/scalardl/Chart.yaml
  charts/scalardl/README.md
  charts/scalardl/values.yaml
  charts/schema-loading/Chart.yaml
  charts/schema-loading/README.md
  charts/schema-loading/values.yaml
Labels: bugfix

#97 Update Envoy Helm Chart to 2.1.0 (use scalar-envoy 1.3.0)
  charts/envoy/Chart.yaml
  charts/envoy/README.md
  charts/envoy/values.yaml
Labels: enhancement

#94 Configure Grafana to allow the embedding feature
  docs/conf/scalar-prometheus-custom-values.yaml
Labels: improvement

#98 Use Secret resource for username and password in the Scalar DB chart
  charts/scalardb/templates/scalardb/configmap.yaml
  charts/scalardb/templates/scalardb/deployment.yaml
  charts/scalardb/templates/scalardb/secret.yaml
Labels: improvement

#99 Remove chart testing for Kubernetes v1.18
  .github/workflows/helm_charts_scalar.yml
Labels: improvement

#100 Use default port in the chart of Scalar DB and Auditor
  charts/scalardb/README.md
  charts/scalardb/templates/scalardb/deployment.yaml
  charts/scalardb/values.yaml
  charts/scalardl-audit/README.md
  charts/scalardl-audit/templates/auditor/deployment.yaml
  charts/scalardl-audit/values.yaml
Labels: improvement
