Repository scalar-labs/helm-charts, pull requests merged in 2022-07, with the labels that each got.

#109 Create a new Helm Chart for Scalar Manager
  charts/scalar-manager/.helmignore
  charts/scalar-manager/Chart.yaml
  charts/scalar-manager/README.md
  charts/scalar-manager/README.md.gotmpl
  charts/scalar-manager/templates/_helpers.tpl
  charts/scalar-manager/templates/deployment.yaml
  charts/scalar-manager/templates/role.yaml
  charts/scalar-manager/templates/rolebinding.yaml
  charts/scalar-manager/templates/service.yaml
  charts/scalar-manager/templates/serviceaccount.yaml
  charts/scalar-manager/values.schema.json
  charts/scalar-manager/values.yaml
  docs/conf/scalar-manager-custom-values.yaml
  docs/getting-started-scalar-helm-charts.md
  docs/getting-started-scalar-manager.md
Labels: enhancement

#96 Support customized database.properties in Scalar DB
  charts/scalardb/README.md
  charts/scalardb/templates/scalardb/configmap.yaml
  charts/scalardb/templates/scalardb/deployment.yaml
  charts/scalardb/values.schema.json
  charts/scalardb/values.yaml
Labels: enhancement

#102 Support customized ledger.properties in Scalar DL Ledger
  charts/scalardl/README.md
  charts/scalardl/templates/ledger/configmap.yaml
  charts/scalardl/templates/ledger/deployment.yaml
  charts/scalardl/values.schema.json
  charts/scalardl/values.yaml
Labels: enhancement

#103 Support customized auditor.properties in Scalar DL Auditor
  charts/scalardl-audit/README.md
  charts/scalardl-audit/templates/auditor/configmap.yaml
  charts/scalardl-audit/templates/auditor/deployment.yaml
  charts/scalardl-audit/values.schema.json
  charts/scalardl-audit/values.yaml
Labels: enhancement

#104 Add doc how to use customized porperties file
  docs/README.md
  docs/how-to-use-customized-configuration.md
Labels: documentation

#114 Update chart version to keep main branch latest (Scalar DB)
  charts/scalardb/Chart.lock
  charts/scalardb/Chart.yaml
  charts/scalardb/README.md
  charts/scalardb/values.yaml
Labels: bugfix

#115 Remove Scalar Manager from index.yaml to make it invisible
  index.yaml
Labels: bugfix

#116 Add default security context in Scalar DL (Ledger/Auditor) chart
  charts/scalardl-audit/README.md
  charts/scalardl-audit/values.schema.json
  charts/scalardl-audit/values.yaml
  charts/scalardl/README.md
  charts/scalardl/values.schema.json
  charts/scalardl/values.yaml
Labels: improvement

#117 Remove unnecessary capabilities from Scalar DB and Envoy chert
  charts/envoy/README.md
  charts/envoy/values.schema.json
  charts/envoy/values.yaml
  charts/scalardb/README.md
  charts/scalardb/values.schema.json
  charts/scalardb/values.yaml
Labels: improvement

#119 Disable seccomp checking in CI (kubeaudit)
  .github/kube-audit.yaml
Labels: bugfix

#121 Remove inappropriate default values in Envoy chart
  charts/envoy/README.md
  charts/envoy/values.schema.json
  charts/envoy/values.yaml
Labels: improvement

#122 Remove unnecessary envoy default setting from each chart
  charts/scalardb/README.md
  charts/scalardb/values.schema.json
  charts/scalardb/values.yaml
  charts/scalardl-audit/README.md
  charts/scalardl-audit/values.schema.json
  charts/scalardl-audit/values.yaml
  charts/scalardl/README.md
  charts/scalardl/values.schema.json
  charts/scalardl/values.yaml
Labels: improvement

#123 Set `automountServiceAccountToken: false` in Ledger and Auditor chart
  charts/scalardl-audit/templates/auditor/deployment.yaml
  charts/scalardl/templates/ledger/deployment.yaml
Labels: improvement

#120 Disable Pod Security Policy by default in Envoy chart
  charts/envoy/README.md
  charts/envoy/values.yaml
Labels: improvement
