Repository scalar-labs/helm-charts, pull requests merged in 2024-02, with the labels that each got.

#248 Revise the `Getting Started Monitoring` guide to support Scalar Manager
  docs/getting-started-monitoring.md
Labels: improvement

#251 Revise the document of scalar-admin-for-kubernetes
  docs/configure-custom-values-scalar-admin-for-kubernetes.md
Labels: documentation

#249 Revise scalar-loki-stack-custom-values.yaml to scrape the logs of scalar-admin-for-kubernetes
  docs/conf/scalar-loki-stack-custom-values.yaml
Labels: enhancement

#252 Add notice about the relocation of docs
  docs/README.md
  docs/ReleaseFlow.md
  docs/configure-custom-values-envoy.md
  docs/configure-custom-values-file.md
  docs/configure-custom-values-scalar-admin-for-kubernetes.md
  docs/configure-custom-values-scalar-manager.md
  docs/configure-custom-values-scalardb-analytics-postgresql.md
  docs/configure-custom-values-scalardb-cluster.md
  docs/configure-custom-values-scalardb-graphql.md
  docs/configure-custom-values-scalardb.md
  docs/configure-custom-values-scalardl-auditor.md
  docs/configure-custom-values-scalardl-ledger.md
  docs/configure-custom-values-scalardl-schema-loader.md
  docs/getting-started-logging.md
  docs/getting-started-monitoring.md
  docs/getting-started-scalar-helm-charts.md
  docs/getting-started-scalar-manager.md
  docs/getting-started-scalardb-analytics-postgresql.md
  docs/getting-started-scalardb.md
  docs/getting-started-scalardl-auditor.md
  docs/getting-started-scalardl-ledger.md
  docs/how-to-deploy-scalar-admin-for-kubernetes.md
  docs/how-to-deploy-scalar-manager.md
  docs/how-to-deploy-scalar-products.md
  docs/how-to-deploy-scalardb-analytics-postgresql.md
  docs/how-to-deploy-scalardb-cluster.md
  docs/how-to-deploy-scalardb-graphql.md
  docs/how-to-deploy-scalardb.md
  docs/how-to-deploy-scalardl-auditor.md
  docs/how-to-deploy-scalardl-ledger.md
  docs/mount-files-or-volumes-on-scalar-pods.md
  docs/samples/scalardb/scalardb-multi-storage-sample/README.md
  docs/samples/scalardl/scalardl-auditor-mode-sample/README.md
  docs/use-secret-for-credentials.md
Labels: documentation
